### PR TITLE
[Filestore] fix linkage error after #4283

### PR DESCRIPTION
**Pull request by SvartMetal**
Error was introduced in #4283.
When building with `-D FORCE_STATIC_LINKING=yes` we get:
```
ld.lld: error: duplicate symbol: fuse_reply_none
>>> defined at fuse_lowlevel.c:304 (/home/svartmetal/nbs-github2/contrib/libs/virtiofsd/fuse_lowlevel.c:304)
>>>            fuse_lowlevel.c.o:(fuse_reply_none) in archive contrib/libs/virtiofsd/static/libvirtiofsd.a
>>> defined at fuse_virtio.c:373 (/home/svartmetal/nbs-github2/cloud/filestore/libs/vfs_fuse/vhost/fuse_virtio.c:373)
>>>            fuse_virtio.c.o:(.text.fuse_reply_none+0x0) in archive cloud/filestore/libs/vfs_fuse/vhost/liblibs-vfs_fuse-vhost.a
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

### CODE REVIEW

File: cloud/filestore/libs/vfs_fuse/fuse.cpp [hunk 1]
```diff
@@ -16,3 +16,8 @@ int fuse_cancel_request(
     (void)code;
     return fuse_reply_err(req, EINTR);
 }
+
+void fuse_reply_none_override(fuse_req_t req)
```
Comment (budevg) [inline cloud/filestore/libs/vfs_fuse/fuse.cpp:20]: since it became virtio specific function lets' just call it `virtio_reply_none`

Comment (SvartMetal) [reply cloud/filestore/libs/vfs_fuse/fuse.cpp:20]: I prefer to keep the current naming because virtio implementation is switchable using compile-time flag `FUSE_VIRTIO`, we have classic FUSE implementation when this flag is off

Comment (SvartMetal) [reply cloud/filestore/libs/vfs_fuse/fuse.cpp:20]: Added comment in code

**Review by budevg — APPROVED** [review]
